# Generated by Django 2.1.7 on 2019-03-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_sell', '0002_auto_20190308_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
