# Generated by Django 2.1.7 on 2019-03-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_sell', '0003_auto_20190308_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('UP', 'UP'), ('Orissa', 'Orissa'), ('Haryana', 'Haryana'), ('Meghalaya', 'Meghalaya')], default='Punjab', max_length=25),
        ),
    ]
