# Generated by Django 2.1.7 on 2019-03-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20190308_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='pesticides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='crops',
            name='pesticides',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='farmer.pesticides'),
        ),
    ]
