# Generated by Django 2.1.7 on 2019-03-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20190308_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crops',
            name='pesticides',
        ),
        migrations.AddField(
            model_name='crops',
            name='pesticides',
            field=models.ManyToManyField(to='farmer.pesticides'),
        ),
    ]
